# Generated by Django 3.1.6 on 2021-02-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='status_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='selected_tasks',
        ),
        migrations.AddField(
            model_name='profile',
            name='selected_tasks',
            field=models.ManyToManyField(null=True, to='todolist.Tasks', verbose_name='Выбранные задачи'),
        ),
    ]
