# Generated by Django 3.1.6 on 2021-02-15 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20210215_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.tasks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.profile')),
            ],
        ),
    ]
