# Generated by Django 3.1.6 on 2021-02-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_user_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='selected_tasks',
            field=models.ManyToManyField(to='todolist.Tasks'),
        ),
    ]
